from .cameras import CamerasFile
from .customtriggers import CustomTriggersFile
from .doodads import DoodadsFile
from .imports import ImportsFile
from .map import MapFile
from .metadata import MetadataFile
from .minimapicons import MinimapIconsFile
from .objects import ObjectsFile
from .objectswithvariations import ObjectsWithVariationsFile
from .pathmap import PathMapFile
from .regions import RegionsFile
from .shadowmap import ShadowMapFile
from .sounds import SoundsFile
from .tilemap import TileMapFile
from .triggers import TriggersFile
from .unitdoodads import UnitDoodadsFile
